import { NextResponse } from "next/server";
import { z } from "zod";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import {
  verifyTotpToken,
  generateRecoveryCodes,
  hashRecoveryCode,
} from "@/lib/totp";

const schema = z.object({
  code: z.string().length(6),
});

/**
 * Confirms the first TOTP code generated by the user's authenticator app,
 * turns 2FA on, and issues a fresh batch of recovery codes (shown to the
 * user exactly once in the response).
 */
export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const body = await request.json();
  const parsed = schema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid code" }, { status: 400 });
  }

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
  });
  if (!user) {
    return NextResponse.json({ error: "User not found" }, { status: 404 });
  }

  const codeValid =
    user.totpSecret && verifyTotpToken(parsed.data.code, user.totpSecret);

  if (!codeValid) {
    return NextResponse.json(
      { error: "Code is invalid or expired" },
      { status: 400 },
    );
  }

  await prisma.user.update({
    where: { id: user.id },
    data: { totpEnabled: true },
  });

  // Issue a fresh batch of recovery codes, replacing any existing ones.
  const recoveryCodes = generateRecoveryCodes();
  await prisma.recoveryCode.deleteMany({ where: { userId: user.id } });
  await prisma.recoveryCode.createMany({
    data: await Promise.all(
      recoveryCodes.map(async (code) => ({
        userId: user.id,
        codeHash: await hashRecoveryCode(code),
      })),
    ),
  });

  return NextResponse.json({ success: true, recoveryCodes });
}
